# Generated by Django 3.1.3 on 2020-11-25 14:38

from django.db import migrations, models
import phonenumber_field.modelfields


PROVINCES = (
    ("CTM", "Covid Tracing Mongolia"),
)


def add_provinces(apps, schema_editor):
    # We can't import the HealthcareProvince model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Province = apps.get_model("profiles", "HealthcareProvince")
    for _abbr, _name in PROVINCES:
        temp = Province(abbr=_abbr, name=_name)
        temp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20201113_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarefailedaccessattempt',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Оролдсон цаг'),
        ),
        migrations.AlterField(
            model_name='healthcareuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='Хэрвээ тохируулсан бол, хэрэглэгч энэ цаг хүртэл блок хийгдэнэ.', null=True),
        ),
        migrations.AlterField(
            model_name='healthcareuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Бүтэн нэр'),
        ),
        migrations.AlterField(
            model_name='healthcareuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Нэвтрэх болгондоо та шинэ нууц код авч оруулах ёстой. Нууц кодыг таны гар утасруу явуулах болно.', max_length=128, region=None),
        ),
        migrations.RunPython(add_provinces),
    ]
